# Copyright 2026 ACSONE SA/NV (<https://acsone.eu>)
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl)

from odoo.addons.component.tests.common import TransactionComponentCase

# Excerpt of a 'requirements.txt' frozen by pip-deepfreeze
REQUIREMENTS = """\
# frozen requirements generated by pip-deepfreeze
aiohttp==3.14.3
click-odoo==1.8.0
gitpython==3.1.58
odoo @ git+https://github.com/acsone/odoo.git@8cc9bd3c893dfd8b43b4f1af287e5e9f
odoo-addon-base-time-window==18.0.1.1.1
odoo-addon-component==18.0.1.0.5.1
odoo-addon-web-responsive==18.0.1.0.7
odoo-addons-parser==0.8
"""


class TestRequirementsTxtResolver(TransactionComponentCase):
    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        cls.backend = cls.env.ref("odoo_repository.mca_backend")

    def _resolve(self, content):
        with self.backend.work_on("odoo.project") as work:
            resolver = work.component(
                usage="project.dependency.resolver.requirements_txt"
            )
            return resolver.resolve(content)

    def _resolve_one(self, requirement):
        dependencies = self._resolve(requirement)
        self.assertEqual(len(dependencies), 1, requirement)
        return dependencies[0]

    def test_resolve_keeps_addons_only(self):
        """Only the addons of a requirements file are resolved."""
        dependencies = self._resolve(REQUIREMENTS)
        self.assertEqual(
            [dependency.module_name for dependency in dependencies],
            ["base_time_window", "component", "web_responsive"],
        )

    def test_resolve_odoo_itself_is_not_an_addon(self):
        """The 'odoo' requirement pins the core, not a module."""
        self.assertFalse(
            self._resolve("odoo @ git+https://github.com/odoo/odoo.git@a1")
        )

    def test_resolve_lookalike_distribution(self):
        """'odoo-addons-parser' is a library, not an addon."""
        self.assertFalse(self._resolve("odoo-addons-parser==0.8"))

    def test_resolve_version(self):
        """A pinned version is the version of the module."""
        dependency = self._resolve_one("odoo-addon-web-responsive==18.0.1.0.7")
        self.assertEqual(dependency.version, "18.0.1.0.7")
        self.assertFalse(dependency.is_pinned)

    def test_resolve_version_drops_the_packaging_serial(self):
        """A serial appended by the packaging is not part of the manifest version."""
        dependency = self._resolve_one("odoo-addon-odoo-repository==18.0.1.2.0.3")
        self.assertEqual(dependency.module_name, "odoo_repository")
        self.assertEqual(dependency.version, "18.0.1.2.0")

    def test_resolve_version_drops_the_local_segment(self):
        dependency = self._resolve_one("odoo-addon-component==18.0.1.0.5+local")
        self.assertEqual(dependency.version, "18.0.1.0.5")

    def test_resolve_unpinned_requirement(self):
        """A requirement without an exact version yields no version."""
        dependency = self._resolve_one("odoo-addon-component>=18.0.1.0.5")
        self.assertEqual(dependency.module_name, "component")
        self.assertFalse(dependency.version)

    def test_resolve_legacy_prefix(self):
        """Addons were distributed as 'odoo<series>-addon-' before 15.0."""
        dependency = self._resolve_one("odoo14-addon-web-responsive==14.0.1.0.1")
        self.assertEqual(dependency.module_name, "web_responsive")

    def test_resolve_pinned_on_a_fork(self):
        """A fork commit is recorded as the origin of the module."""
        dependency = self._resolve_one(
            "odoo-addon-account-invoice-triple-discount @ "
            "git+https://github.com/acsone/account-invoicing.git"
            "@3e4c54bb1a3a34b4b031b3dec9ccf6b2997d1295"
            "#subdirectory=setup/account_invoice_triple_discount"
        )
        self.assertEqual(dependency.module_name, "account_invoice_triple_discount")
        self.assertEqual(
            dependency.clone_url, "https://github.com/acsone/account-invoicing.git"
        )
        self.assertEqual(dependency.ref, "3e4c54bb1a3a34b4b031b3dec9ccf6b2997d1295")
        self.assertEqual(
            dependency.subdirectory, "setup/account_invoice_triple_discount"
        )
        self.assertTrue(dependency.is_pinned)
        # A revision carries no version
        self.assertFalse(dependency.version)

    def test_resolve_pinned_on_a_pull_request(self):
        """A PR ref holds slashes, which must not be mistaken for a path."""
        dependency = self._resolve_one(
            "odoo-addon-account-invoice-triple-discount @ "
            "git+https://github.com/OCA/account-invoicing.git"
            "@refs/pull/2279/head"
            "#subdirectory=setup/account_invoice_triple_discount"
        )
        self.assertEqual(
            dependency.clone_url, "https://github.com/OCA/account-invoicing.git"
        )
        self.assertEqual(dependency.ref, "refs/pull/2279/head")

    def test_resolve_subdirectory_wins_over_the_distribution_name(self):
        """The subdirectory names the module, the distribution name is normalized."""
        dependency = self._resolve_one(
            "odoo-addon-l10n-be-coa-multilang @ "
            "git+https://github.com/OCA/l10n-belgium.git@18.0"
            "#subdirectory=setup/l10n_be_coa_multilang"
        )
        self.assertEqual(dependency.module_name, "l10n_be_coa_multilang")

    def test_resolve_url_with_credentials(self):
        """Credentials in the URL are not mistaken for a revision separator."""
        dependency = self._resolve_one(
            "odoo-addon-component @ "
            "git+https://user@example.com/acsone/addons.git@18.0"
            "#subdirectory=setup/component"
        )
        self.assertEqual(
            dependency.clone_url, "https://user@example.com/acsone/addons.git"
        )
        self.assertEqual(dependency.ref, "18.0")

    def test_resolve_ignores_comments_and_options(self):
        content = (
            "# a comment\n"
            "-r base.txt\n"
            "--index-url https://example.com/simple\n"
            "odoo-addon-component==18.0.1.0.5  # trailing comment\n"
        )
        dependency = self._resolve_one(content)
        self.assertEqual(dependency.module_name, "component")
        self.assertEqual(dependency.version, "18.0.1.0.5")

    def test_resolve_ignores_environment_markers(self):
        dependency = self._resolve_one(
            'odoo-addon-component==18.0.1.0.5 ; python_version >= "3.10"'
        )
        self.assertEqual(dependency.version, "18.0.1.0.5")

    def test_resolve_joins_continuation_lines(self):
        content = (
            "odoo-addon-component==18.0.1.0.5 \\\n"
            "    --hash=sha256:0000000000000000000000000000000000000000\n"
        )
        dependency = self._resolve_one(content)
        self.assertEqual(dependency.version, "18.0.1.0.5")

    def test_resolve_empty_content(self):
        self.assertEqual(self._resolve(""), [])
